#include <iostream>
#include <fstream>
// Include the header file generated by protoc
#include "onnx.pb.h" 

int main(int argc, char* argv[]) {
    if(argc < 2){
        std::cout << "Use this executable as ./exe_name model.onnx\n";
        return 0;
    }
    // 1. Verify your Protobuf runtime matches your generated headers
    GOOGLE_PROTOBUF_VERIFY_VERSION;

    // 2. Open the .onnx binary file
    std::ifstream input(argv[1], std::ios::in | std::ios::binary);
    if (!input) {
        std::cerr << "Failed to open the ONNX file.\n";
        return 1;
    }

    // 3. Instantiate the root object and parse the stream
    onnx::ModelProto model;
    if (!model.ParseFromIstream(&input)) {
        std::cerr << "Failed to parse ONNX protobuf data.\n";
        return 1;
    }

    // 4. Extract top-level Model metadata
    std::cout << "ONNX IR Version: " << model.ir_version() << "\n";
    std::cout << "Model Version: " << model.model_version() << "\n";
    std::cout << "Producer Name: " << model.producer_name() << "\n";
    std::cout << "Producer Version: "<< model.producer_version() << "\n";

    // 5. Get a reference to the Graph
    const onnx::GraphProto& graph = model.graph();

    // 6. Loop through the initializers using the _size() syntax
    std::cout << "\nTotal Initializers: " << graph.initializer_size() << "\n\n";
    
    for (int i = 0; i < graph.initializer_size(); ++i) {
        // Access each individual tensor weight
        const onnx::TensorProto& tensor = graph.initializer(i);
        
        std::cout << "Initializer [" << i << "] Name: " << tensor.name() << "\n";
        std::cout << "  Dimensions: [";
        for (int j = 0; j < tensor.dims_size(); ++j) {
            std::cout << tensor.dims(j) << (j == tensor.dims_size() - 1 ? "" : ", ");
        }
        std::cout << "]\n\n";
    }

    // Optional: Clean up Protocol Buffers allocations
    google::protobuf::ShutdownProtobufLibrary();
    return 0;
}